# Uncomment the next line to define a global platform for your project
 platform :ios, '10.3'

target 'BlockathonDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BlockathonDemo
  pod 'Alamofire', '~> 4.4.0'
  pod "EVReflection", :git => 'https://github.com/evermeer/EVReflection.git', :branch => 'Swift3.0'
  pod 'AlamofireNetworkActivityLogger', '~> 2.0'
  pod 'AlamofireJsonToObjects'
  pod 'SwiftyJSON'
	pod 'SWRevealViewController'
end
