# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlockathonDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BlockathonDemo
  pod 'Alamofire', '~> 4.5'
  pod "EVReflection/Alamofire"
  pod 'AlamofireNetworkActivityLogger', '~> 2.0'
  pod 'AlamofireJsonToObjects'
  pod 'SwiftyJSON'
end
